///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//
//import java.awt.EventQueue;
//import java.util.Calendar;
//import java.time.LocalDate;
//import java.time.LocalDateTime;
//import java.time.format.DateTimeFormatter;
//import javax.swing.JOptionPane;
//import java.sql.*;
//import java.text.DateFormat;
//import java.text.SimpleDateFormat;
//
//import javax.swing.JOptionPane;
//
///**
// *
// * @author Hantao
// */
//public class DailyTracker extends javax.swing.JFrame implements Runnable{
//
//    Thread t;
//    int hcnt=0, mcnt=0, scnt=0;
//    String str="", mstr="", dstr="",nstr="";
//    int cnt=0, cnt2=0;
//
//    /**
//     * Creates new form DailyTracker
//     */
//
//    Connection connection=null;
//
//    public DailyTracker() {
//        initComponents();
//        t= new Thread(this);
//	reset();
//        connection=DBConnection.connect();
//    }
//
//    public void reset(){
//
//	hcnt=0;mcnt=0;scnt=0;cnt2=0;
//	nstr="00:00:00";dstr="";
//	display();
//    }
//
//    public void display(){
//
//	Timer.setText(nstr);
//
//    }
//
//    public void setTimeCounter(){
//	nstr="";
//	if (hcnt<10){
//		nstr="0"+hcnt;
//	} else
//            {
//		nstr=""+hcnt;
//            }
//	if (mcnt<10)
//            {
//		nstr+=":0"+mcnt;
//            }   else
//            {
//		nstr+=":"+mcnt;
//
//            }
//	if (scnt<10)
//		{
//			nstr+=":0"+scnt;
//		}
//		else
//		{
//			nstr+=":"+scnt;
//
//		}
//	}
//
//
//    public void run()
//	{
//		try
//		{
//			while(true)
//			{
//				scnt++;
//				if (scnt>59)
//				{
//					scnt=0;
//					mcnt++;
//				}
//				if (mcnt>59)
//				{
//					mcnt=0;
//					hcnt++;
//				}
//				if (hcnt>99)
//				{
//					reset();
//				}
//				setTimeCounter();
//				display();
//				Thread.sleep(1000);
//
//			}
//		} catch (Exception e){}
//    }
//
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        jPanel1 = new javax.swing.JPanel();
//        Timer = new javax.swing.JLabel();
//        btnStart = new javax.swing.JButton();
//        btnReset = new javax.swing.JButton();
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        InPush = new javax.swing.JTextField();
//        InRun = new javax.swing.JTextField();
//        RecordPush = new javax.swing.JButton();
//        RecordRun = new javax.swing.JButton();
//        jLabel3 = new javax.swing.JLabel();
//        MaxPush = new javax.swing.JLabel();
//        jLabel5 = new javax.swing.JLabel();
//        MaxRun = new javax.swing.JLabel();
//        Date = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//        jButton1 = new javax.swing.JButton();
//        jButton2 = new javax.swing.JButton();
//        jTextField1 = new javax.swing.JTextField();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        Timer.setFont(new java.awt.Font("Digital-7 Mono", 1, 48)); // NOI18N
//        Timer.setText("88:88:88");
//
//        btnStart.setText("Start");
//        btnStart.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnStartActionPerformed(evt);
//            }
//        });
//
//        btnReset.setText("Reset");
//        btnReset.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnResetActionPerformed(evt);
//            }
//        });
//
//        jLabel1.setText("Pushups");
//
//        jLabel2.setText("RunningMiles");
//
//        InPush.setText("0");
//        InPush.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                InPushActionPerformed(evt);
//            }
//        });
//
//        InRun.setText("0");
//        InRun.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                InRunActionPerformed(evt);
//            }
//        });
//
//        RecordPush.setText("Record");
//        RecordPush.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                RecordPushActionPerformed(evt);
//            }
//        });
//
//        RecordRun.setText("Record");
//        RecordRun.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                RecordRunActionPerformed(evt);
//            }
//        });
//
//        jLabel3.setText("Max Pushups");
//
//        MaxPush.setText("0");
//
//        jLabel5.setText("Max Running Miles");
//
//        MaxRun.setText("0");
//
//
//
//
//        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
//        LocalDate localDate = LocalDate.now();
//        Date.setText(dtf.format(localDate));
//
//        jLabel4.setFont(new java.awt.Font("Digital-7 Mono", 3, 48)); // NOI18N
//        jLabel4.setText("88:88:88");
//
//        jButton1.setText("Start");
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//
//        jButton2.setText("Reset");
//
//        jTextField1.setText("00:00:00");
//        jTextField1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField1ActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
//                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jLabel2)
//                            .addComponent(jLabel1))
//                        .addGap(59, 59, 59)
//                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                            .addComponent(InPush, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
//                            .addComponent(InRun))
//                        .addGap(27, 27, 27)
//                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(RecordPush)
//                            .addComponent(RecordRun))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(MaxRun)
//                        .addGap(171, 171, 171))
//                    .addGroup(jPanel1Layout.createSequentialGroup()
//                        .addGap(0, 0, Short.MAX_VALUE)
//                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addGroup(jPanel1Layout.createSequentialGroup()
//                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addComponent(jLabel3)
//                                .addGap(18, 18, 18)
//                                .addComponent(MaxPush))
//                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                                .addComponent(Timer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addGroup(jPanel1Layout.createSequentialGroup()
//                                    .addComponent(btnStart)
//                                    .addGap(97, 97, 97)
//                                    .addComponent(btnReset))))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                                .addComponent(jLabel5)
//                                .addGap(195, 195, 195))
//                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                                    .addComponent(jButton1)
//                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                    .addComponent(jButton2)
//                                    .addGap(26, 26, 26))
//                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                    .addContainerGap()))))))
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(23, 23, 23)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel1)
//                    .addComponent(InPush, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(RecordPush))
//                .addGap(31, 31, 31)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel2)
//                    .addComponent(InRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(RecordRun))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel3)
//                    .addComponent(MaxPush)
//                    .addComponent(jLabel5)
//                    .addComponent(MaxRun))
//                .addGap(27, 27, 27)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(Timer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(18, 18, 18)
//                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(15, 15, 15)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(btnStart)
//                    .addComponent(btnReset)
//                    .addComponent(jButton1)
//                    .addComponent(jButton2))
//                .addGap(25, 25, 25))
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 79, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>
//
//    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {
//        if (btnStart.getText().equals("Start")){
//             btnStart.setText("Stop");
//             cnt++;
//             if (cnt==1)
//             {
//                 t.start();
//             }
//             else
//             {
//                 t.resume();
//             }
//        }
//        else
//        {
//            btnStart.setText("Start");
//            t.suspend();
//
//        }
//    }
//
//    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {
//        reset();
//        t.suspend();
//        btnStart.setText("Start");
//
//    }
//
//    private void InRunActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    private void InPushActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    private void RecordPushActionPerformed(java.awt.event.ActionEvent evt) {
//         int pushNums;
//         try{
//                pushNums = Integer.parseInt(InPush.getText());
//                MaxPush.setText(Integer.toString(pushNums));
//
//		}catch(Exception e1) {
//                JOptionPane.showMessageDialog(null, "Please Enter a Valid Number");
//
//	}
//    }
//
//    private void RecordRunActionPerformed(java.awt.event.ActionEvent evt) {
//        int RunningNum;
//        try{
//                RunningNum = Integer.parseInt(InRun.getText());
//                MaxRun.setText(Integer.toString(RunningNum));
//
//		}catch(Exception e1) {
//                JOptionPane.showMessageDialog(null, "Please Enter a Valid Number");
//
//	}
//    }
//
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DailyTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DailyTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DailyTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DailyTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DailyTracker().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify
//    private javax.swing.JLabel Date;
//    private javax.swing.JTextField InPush;
//    private javax.swing.JTextField InRun;
//    private javax.swing.JLabel MaxPush;
//    private javax.swing.JLabel MaxRun;
//    private javax.swing.JButton RecordPush;
//    private javax.swing.JButton RecordRun;
//    private javax.swing.JLabel Timer;
//    private javax.swing.JButton btnReset;
//    private javax.swing.JButton btnStart;
//    private javax.swing.JButton jButton1;
//    private javax.swing.JButton jButton2;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JTextField jTextField1;
//    // End of variables declaration
//}
